apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: apps
    repoURL: 'https://github.com/legmac/argo.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
