apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: dev
  source:
    path: apps/
    repoURL: https://github.com/legmac/argo.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true