apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    path: apps/
    repoURL: https://github.com/legmac/argo.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true