apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-admin
  namespace: monitoring
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:  
  destination:
    namespace: monitoring
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: spring-boot-admin
    helm:
      valueFiles:
        - values.yaml
    repoURL: 'https://evryfs.github.io/helm-charts/'
    targetRevision: 0.0.11

