apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-admin
  namespace: default
spec:  
  project: default
  source:
    repoURL: 'https://evryfs.github.io/helm-charts/'
    targetRevision: 0.0.11
    helm:
    chart: spring-boot-admin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true